# fly.toml app configuration file generated for file-library-translink on 2026-06-13T09:55:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'file-library-translink'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = "10s"
  timeout = "5s"
  method = "GET"
  path = "/healthz.php"
  grace_period = "30s"

[env]
  DB_DRIVER = "pgsql"
  DB_HOST = "localhost"
  DB_PORT = "5432"
  DB_NAME = "translink_gps"
  DB_USER = "postgres"
  DB_PASS = "postgres"
  SITE_URL = "https://file-library-translink.fly.dev"
  DEBUG = "false"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
